--Create table
CREATE TABLE player (
  id INT,
  codename VARCHAR(30)
);

--Place first record into table
INSERT INTO player (id, codename)
VALUES (1, 'Opus');
VALUES (2, 'Mario');
VALUES (12345, "newCodeName")

VALUES (, b);
VALUES (, ba);
VALUES (, ban);
VALUES (, bana);
VALUES (, banan);
VALUES (, banana);
VALUES (2, );
VALUES (22, );
VALUES (222, );
VALUES (2222, );
VALUES (22222, );
VALUES (222222, );
VALUES (2222222, );
VALUES (22222222, );
VALUES (, t);
VALUES (, te);
VALUES (, tes);
VALUES (, test);
VALUES (, testi);
VALUES (, testin);
VALUES (1, );
VALUES (12, );
VALUES (123, );
VALUES (, s);
VALUES (, st);
VALUES (, sti);
VALUES (, stil);
VALUES (, still);
VALUES (, stillt);
VALUES (, stillte);
VALUES (, stilltes);
VALUES (, stilltest);
VALUES (, stilltestg);
VALUES (, stilltest);
VALUES (, stilltesti);
VALUES (, stilltestin);
VALUES (, stilltesting);
VALUES (1, );
VALUES (12, );
VALUES (123, );
VALUES (1234, );
VALUES (2, );
VALUES (23, );
VALUES (234, );
VALUES (, b);
VALUES (, ba);
VALUES (, ban);
VALUES (, bana);
VALUES (, banan);
VALUES (, banana);
VALUES (, banan);
VALUES (, bana);
VALUES (, ban);
VALUES (, ba);
VALUES (, b);
VALUES (, );
VALUES (, s);
VALUES (, st);
VALUES (, sti);
VALUES (, stil);
VALUES (, still);
VALUES (, stillt);
VALUES (, stillte);
VALUES (, stilltes);
VALUES (, stilltest);
VALUES (, stilltesti);
VALUES (, stilltestin);
VALUES (, stilltesting);
VALUES (, e);
VALUES (, ew);
VALUES (, ewe);
VALUES (, ewew);
VALUES (1, );
VALUES (12, );
VALUES (123, );
VALUES (1231, );
VALUES (12312, );
VALUES (, h);
VALUES (, ha);
VALUES (, hah);
VALUES (, haha);
VALUES (, hahah);
VALUES (, hahaha);
VALUES (, hahah);
VALUES (, haha);
VALUES (, hah);
VALUES (, ha);
VALUES (, h);
VALUES (, );
VALUES (, g);
VALUES (, go);
VALUES (, got);
VALUES (, got );
VALUES (, got i);
VALUES (, got it);
VALUES (, got i);
VALUES (, got );
VALUES (, got);
VALUES (, got );
VALUES (, got i);
VALUES (, got it);
VALUES (2, );
VALUES (22, );
VALUES (222, );
VALUES (2221, );
VALUES (, g);
VALUES (, go);
VALUES (, got);
VALUES (, got );
VALUES (, got i);
VALUES (, got it);
VALUES (, got it?);
VALUES (2, );
VALUES (22, );
VALUES (222, );